server.port=8080
server.tomcat.threads.max=30

spring.application.name=mars

spring.datasource.url=jdbc:mysql://localhost:3306/Mars?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=01234567890123456789012345678901
jwt.expiration=86400000
